spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-id
            client-secret: test-secret
            scope:
              - email
              - profile
jwt:
  issuer: jmpark6846@naver.com
  secret_key: testsecret




